import {assets} from './assets.js';

// Everything in this prototype is local demo data. No credentials or payments are sent.
const app=document.querySelector('#app');
const dialog=document.querySelector('#dialog');
const initial={email:'',name:'John Smith',company:'ACME Protocol',website:'https://acme.com',address:'0x2c00000000000000000000000000000000004567',network:'Ethereum',whitepaper:'',paymentNetwork:'',description:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tempus turpis. Sed varius accumsan nibh, sit amet molestie orci vestibulum sit amet. Aliquam sit amet ex pellentesque, auctor erat sit amet, cursus dolor. Donec nec turpis libero. Nunc sed dui ut erat vulputate ullamcorper. Vivamus et ipsum non turpis facilisis interdum.',completed:1,inactive:false,logo:'',assetLogo:'',plan:'Starter'};
let state={...initial};
let route='',page=1,query='',sortDirection=0,toastTimer;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=(screen,name,cls='')=>`<img class="${cls}" src="${assets[screen][name]}" alt="" data-asset="${screen}:${name}">`;
const icon=(screen,name)=>`<span class="asset">${image(screen,name)}</span>`;
const divider=(screen,name)=>`<span class="divider">${image(screen,name)}</span>`;
const field=(label,name,placeholder='',type='text',value='',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" placeholder="${escape(placeholder)}" value="${escape(value)}" ${extra}></label>`;
const primary=(text='Continue',extra='')=>`<button class="primary${extra.includes('full')?' full':''}" ${extra.replace(/class="[^"]*"/g,'')}>${text}</button>`;
const networkLogo=value=>icon('network-dropdown',value==='Ethereum'?'imgEthereumEth':'imgPolygon');
const network=(name,value='',required=true)=>`<div class="network-select"><select class="network-native" name="${name}" tabindex="-1" aria-hidden="true" ${required?'required':''}><option value=""></option>${['Ethereum','Polygon'].map(n=>`<option ${value===n?'selected':''}>${n}</option>`).join('')}</select><button type="button" class="network-trigger" role="combobox" aria-label="${name==='paymentNetwork'?'Payment network':'Network'}" aria-haspopup="listbox" aria-expanded="false" aria-controls="${name}-options"><span class="network-value ${value?'':'muted'}">${value?networkLogo(value):''}${value||'Select'+(name==='paymentNetwork'?' network':'')}</span>${icon('network-dropdown','imgGroup5')}</button><div class="network-options hidden" id="${name}-options" role="listbox" aria-label="Available networks">${['Ethereum','Polygon'].map(n=>`<button type="button" role="option" tabindex="-1" aria-selected="${n===value}" data-network="${n}">${networkLogo(n)}<span>${n}</span></button>`).join('')}</div></div>`;
function toast(message){clearTimeout(toastTimer);const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');toastTimer=setTimeout(()=>el.classList.remove('visible'),3500);}
function modal(title,body,actions=''){dialog.innerHTML=`<button class="close-dialog" aria-label="Close dialog" data-action="close">×</button><h2>${title}</h2>${body}${actions}`;dialog.showModal();}
function go(to){if(location.hash.slice(1)===to)render();else location.hash=to;}
function brand(){return `<a href="#signin" aria-label="ONCHAIN Ramp home" class="brand"><span class="brand-word">${image('login','imgGroup18646')}</span><span class="brand-beta">${image('login','imgBeta')}</span><span class="brand-ramp">${image('login','imgRamp')}</span></a>`;}
function footer(auth=false){return `<footer class="footer"><div class="legal"><button data-action="terms">${auth?'Terms of Service':'Terms and Conditions'}</button><button data-action="privacy">Privacy Policy</button></div><button class="support" aria-label="Open support" data-action="support">${image('login','imgFrame18647')}</button></footer>`;}
const screenOptions=[['signin','Sign in'],['verify','Email confirmation'],['details','Company details'],['asset','Digital asset'],['setup/whitepaper','Finish setup'],['dashboard','Dashboard'],['transactions','Transactions'],['settings/project','Settings'],['settings/billing/payment','Billing · Payment details'],['settings/billing/transactions','Billing · Transactions']];
function prototypeNav(){return `<aside class="prototype-nav" aria-label="Prototype controls"><span>Prototype</span><select aria-label="Preview screen">${screenOptions.map(([v,l])=>`<option value="${v}" ${route===v?'selected':''}>${l}</option>`).join('')}</select><button data-action="restart">Restart</button></aside>`;}
function topbar(){return `<header class="topbar"><a class="project-brand" href="#dashboard" style="color:inherit">${state.logo?`<span class="project-logo"><img src="${state.logo}" alt="Company logo"></span>`:`<span class="project-logo placeholder" role="img" aria-label="Company logo not set">${icon('139458','imgImage')}</span>`}<span>${escape(state.company)}</span></a><div class="account"><div class="renew">${state.completed<5?'Trial ends:':'Renews in:'}<strong>12 days</strong></div><button class="outline ramp-link" data-action="ramp">Ramp link ${icon('144812','imgContentCopyFilled')}</button><div class="identity">${escape(state.name)}<span>Administrator</span></div><div class="account-wrap"><button class="account-toggle" aria-label="Account menu" aria-expanded="false" data-action="menu"><span class="avatar">TG</span>${icon('144812','imgGroup2')}</button><nav class="account-menu hidden" aria-label="Account"><a href="#dashboard">Dashboard</a><a href="#transactions">Transactions</a>${state.completed>=5?'<button type="button" disabled aria-disabled="true" title="Setup completed">Finish setup</button>':'<a href="#setup/whitepaper">Finish setup</a>'}<a href="#settings/project">Settings</a><button data-action="signout">Sign out</button></nav></div></div></header>`;}
function authLayout(content,hero=false){return `<header class="auth-header">${brand()}</header><main class="auth-main">${hero?`<div class="auth-hero"><section class="hero-copy"><h1><span>Sell Direct.</span><br>Instantly.</h1><p>The way buying digital assets should have always been.<br><strong style="font-weight:500">No Middlemen—straight from the source.</strong></p></section><section class="login-card">${content}</section></div>`:content}</main>${footer(true)}`;}
function signIn(){return authLayout(`<p class="trial">Start your 14-day <strong>free trial</strong>.</p>${divider('login','imgFrame1707478956')}<h2>Sign in</h2><form id="signin" class="signin-form"><input name="email" type="email" required placeholder="Your Email" aria-label="Your Email" autocomplete="email" value="${escape(state.email)}">${primary('Continue','disabled class="primary"')} </form>`,true);}
function verify(){return authLayout(`<form id="verify" class="otp-content">${icon('139298','imgEnvelope')}<p>We’ve just sent an email to <strong>${escape(state.email||'youremail@yourdomain.com')}</strong><br>Please check your email and enter the confirmation code below.</p><div class="otp">${Array.from({length:6},(_,i)=>`${i===3?'<span class="dash">-</span>':''}<input name="digit${i}" inputmode="numeric" pattern="[0-9]" maxlength="1" required aria-label="Code digit ${i+1}" ${i===0?'autocomplete="one-time-code"':''}>`).join('')}</div><div class="resend">Didn’t get an email?&nbsp; <button type="button" class="link" data-action="resend">Resend code</button></div>${primary('Continue','class="primary full" disabled')}<div class="error" id="otp-error" role="alert"></div></form>`,true);}
function company(){return authLayout(`<form class="auth-card" id="details"><h2>Personal and company details</h2><div class="stack">${field('Full name','name','i.e. John Smith','text','','required autocomplete="name"')}${field('Company name','company','i.e. Your Token LLC','text','','required autocomplete="organization"')}${field('Digital asset website','website','i.e. https://yourtoken.com','url','','required')}</div>${primary('Continue','disabled')}</form>`);}
function asset(){return authLayout(`<form class="auth-card" id="asset"><h2>Digital asset details</h2><div class="stack"><div class="field">Network${network('network')}</div>${field('Address','address','i.e. 0xeef...d3555','text','','required pattern="0x[0-9a-fA-F]{40}" title="Enter a 42-character Ethereum-style address starting with 0x"')}<div><label class="small">Tax <span title="Digital assets with a Buy or Sell tax are currently incompatible with our Sell flow.">ⓘ</span></label><div class="checks">${['Buy tax','Sell tax','N/A'].map(t=>`<label class="check"><input type="checkbox" name="tax" value="${t}">${t}</label>`).join('')}</div></div></div>${primary('Complete sign up','disabled')}<div class="agreements">${['I agree to ONCHAIN® Terms and Conditions and Privacy Policy.','I agree to ONCHAIN® Token Agreement and Terms of Service.','Yes! I’d love to receive updates, exclusive offers, and news from ONCHAIN®. (You can unsubscribe anytime.)'].map((t,i)=>`<label class="check"><input type="checkbox" name="agreement${i}" ${i<2?'required':''}>${t}</label>`).join('')}</div></form>`);}
const steps=[['asset','Digital asset'],['whitepaper','Share your Whitepaper link'],['payment','Choose your payment method'],['plan','Choose your plan'],['verification','Verify your account']];
function setupSidebar(part){const idx=steps.findIndex(s=>s[0]===part);const progress=Math.min(5,state.completed)*20;return `<aside class="sidebar"><div class="sidebar-heading">Finish setup<button aria-label="Close setup" data-action="dashboard">${icon('141560','imgClose')}</button></div><div class="progress" role="progressbar" aria-label="Account setup progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress}" data-progress="${progress}"><div class="fill" style="width:${progress}%"></div><span style="width:${progress}%">${progress}%</span></div><nav class="side-nav">${steps.map(([key,label],i)=>`<a href="#setup/${key}" class="side-link ${idx===i?'active':''} ${i<state.completed?'done':''}">${icon('141560',i<state.completed?'imgGroup1':'imgGroup2')}${label}${i?`<span class="arrow">${icon('141560','imgGroup3')}</span>`:''}</a>`).join('')}</nav></aside>`;}
function setupBody(part){if(part==='asset')return `<h1>Digital asset</h1><p class="subtitle">Your digital asset has cleared.</p><div class="narrow stack">${field('Ticker','ticker','','text','ACME','disabled')}${field('Address','address','','text',state.address,'readonly')}<p class="small">Network: ${escape(state.network)}</p>${primary('Continue','data-go="setup/whitepaper"')}</div>`;
 if(part==='whitepaper')return `<h1>Link to Whitepaper</h1><p class="subtitle">Please provide a link to your projects whitepaper</p><form id="whitepaper" class="narrow stack">${field('Your whitepaper link','whitepaper','Enter your whitepaper link','url',state.whitepaper,'required')}<div class="continue-wrap ${state.whitepaper?'':'hidden'}">${primary('Continue')}</div></form>`;
 if(part==='payment')return `<h1>Payment details</h1><p class="subtitle">Add your preferred payment methods</p><form id="payment"><div class="payment-grid"><div class="stack"><input value="ACME" disabled aria-label="Primary payment currency"><div><label class="small">Secondary payment currency</label><div class="currency-row">${icon('141721','imgUsdc')}USDC ${network('paymentNetwork',state.paymentNetwork)}</div></div><div class="continue-wrap ${state.paymentNetwork?'':'hidden'}">${primary('Continue')}</div></div><aside class="callout"><strong>Pay with your digital asset</strong><p>Token-based projects can settle their subscription fees using the tokens they have issued for their project.<br><button type="button" style="text-decoration:underline" data-action="payment-info">Read more about this</button></p><p><strong>⚠ Sending USDC from a different network than the one selected can result in a permanent loss. Make sure the network matches before proceeding.</strong></p></aside></div></form>`;
 if(part==='plan')return `<div style="padding-top:40px"><h1>Select your plan</h1><p class="subtitle">Activate your plan and start free trial</p><div class="plans">${plan('Starter','$200',false)}${plan('Insights','$500',true)}${plan('Enterprise','On Request',true)}</div></div>`;
 return `<h1>Account Verification</h1><p class="subtitle">To confirm that you are an authorized representative of this token project, please sign in using the project’s official X account (formerly known as Twitter).</p>${state.completed===5?'<button class="x-signed-in narrow full" disabled aria-label="Signed in to X as @acme_labs"><span class="verify-x" aria-hidden="true">𝕏</span>@acme_labs</button><div class="continue-wrap">'+primary('Go to dashboard','data-action="dashboard"')+'</div>':'<button class="outline narrow full" style="border-color:var(--blue)" data-action="verify-x"><span class="verify-x">𝕏</span>Sign in</button>'}<div class="section-line">${divider('142113','imgFrame1707479006')}</div><form id="owner" class="narrow stack ${state.completed===5?'hidden':''}"><h3 style="font-weight:400">Credentials</h3><label class="check muted small"><input type="checkbox" id="email-owner">Email the X account owner</label>${field('Owners email address','owner','Enter owners email address','email','','required disabled')}${primary('Send email','disabled')}</form>`;
}
function plan(name,price,disabled){return `<article class="plan ${disabled?'unavailable':''}"><h3>${name}</h3><div class="price">${price}${name!=='Enterprise'?'<small> / month</small>':''}</div><p>${name==='Starter'?'Free for the first 14 days and then $200 per month':`Everything on ${name==='Insights'?'Starter':'Insights'} plan plus:`}</p><ul>${['Onchain Ramp','Dedicated Dashboard','Payment Links','Pay with your own token','Pay with stable coins'].map(t=>`<li>${icon('142574',disabled?'imgCheckmark1':'imgCheckmark')}${t}</li>`).join('')}</ul>${primary(disabled?'Coming soon':'Choose Starter',disabled?'disabled':'data-action="choose-plan"')}</article>`;}
function setup(part){return `${topbar()}<main class="workspace"><div class="split">${setupSidebar(part)}<section class="content">${setupBody(part)}</section></div></main>${footer()}`;}
const values=[320,580,720,410,530,290,650,470,390,800];const quantities=[987654,543210,321456,654321,789012,234567,876543,345678,210987,456789];
// Stable illustrative identifiers keep search, display, copying, and CSV in sync.
function demoHex(seed,length){let value=seed,hex='';while(hex.length<length){value=(Math.imul(value,1664525)+1013904223)>>>0;hex+=value.toString(16).padStart(8,'0');}return hex.slice(0,length);}
const shortenId=value=>`${value.slice(0,4)}...${value.slice(-4)}`;
const rows=Array.from({length:120},(_,i)=>{const order=demoHex(i*3+3,32);return {id:i,amount:values[i%10]+Math.floor(i/10)*10,quantity:quantities[i%10],status:i%10===1?'Pending':i%10===2?'Failed':'Succeeded',wallet:'0x'+demoHex(i*3+1,40),tx:'0x'+demoHex(i*3+2,64),order:[order.slice(0,8),order.slice(8,12),order.slice(12,16),order.slice(16,20),order.slice(20)].join('-'),date:'Sep 1, 2024, 10:10 pm'};});
function filtered(){let data=rows.filter(r=>`${r.wallet} ${r.order} ${r.status}`.toLowerCase().includes(query.toLowerCase()));if(sortDirection)data=[...data].sort((a,b)=>(a.amount-b.amount)*sortDirection);return data;}
const copyButton=(value,label,large=false)=>`<button class="copy" title="Copy ${escape(value)}" data-copy="${escape(value)}">${escape(label)} ${icon('144812',large?'imgContentCopyFilled1':'imgContentCopyFilled')}</button>`;
function status(s){return `<span class="status ${s}">${icon('144812',s==='Pending'?'imgHourglassAlt':s==='Failed'?'imgGroup1':'imgGroup')}${s}</span>`;}
function tableBody(){const data=filtered();const max=Math.max(1,Math.ceil(data.length/10));page=Math.min(max,Math.max(1,page));return data.slice((page-1)*10,page*10).map(r=>`<tr><td>$${r.amount}<span class="currency">USD</span></td><td>${status(r.status)}</td><td>${r.quantity.toLocaleString('en-US')} ACME</td><td>${copyButton(r.wallet,shortenId(r.wallet))}</td><td>${r.date}</td><td>${copyButton(r.tx,shortenId(r.tx))}</td><td>${copyButton(r.order,shortenId(r.order))}</td></tr><tr class="sep" aria-hidden="true"><td colspan="7">${divider('144812','imgFrame1707478732')}</td></tr>`).join('')||'<tr><td colspan="7"><div class="empty-row">No transactions found. Try a wallet address, order ID, or status.</div></td></tr>';}
function pagination(){const max=Math.max(1,Math.ceil(filtered().length/10));const nums=[...new Set([1,2,3,4,5,page,max])].filter(n=>n<=max).sort((a,b)=>a-b);return `<nav class="pagination" aria-label="Transaction pages"><button data-page="${page-1}" ${page===1?'disabled':''} aria-label="Previous page">${icon('145661','imgGroup5')}</button>${nums.map((n,i)=>`${i&&n-nums[i-1]>1?'<span>…</span>':''}<button data-page="${n}" class="${page===n?'active':''}" ${page===n?'aria-current="page"':''}>${n}</button>`).join('')}<button data-page="${page+1}" ${page===max?'disabled':''} aria-label="Next page">${icon('145661','imgGroup6')}</button></nav>`;}
function digitalAssetLogo(){return state.assetLogo?`<span class="digital-asset-logo"><img src="${state.assetLogo}" alt="Digital asset logo"></span>`:`<span class="digital-asset-logo placeholder" role="img" aria-label="Digital asset logo not set">${icon('139458','imgImage')}</span>`;}
function digital(){return `<section class="panel digital"><h2 class="panel-heading">Digital asset</h2>${divider('144812','imgFrame1707478731')}<div class="digital-grid"><div><label>Ticker ${icon('144812','imgInfoCircle')}</label><div class="token-name">${digitalAssetLogo()}ACME</div></div><div><label>Status</label>${icon('144812','imgStatusActive')}</div><div><label>Address</label>${copyButton(state.address,'0x2c...4567',true)}</div><div><label>Description</label><p class="description">${escape(state.description)}</p></div></div>${divider('144812','imgFrame1707478731')}<div class="pairs-title">Available pairs ${icon('144812','imgInfoCircle')}</div><div class="table-scroll"><div class="pairs-grid header"><span>DEX</span><span>Pair</span><span>Network</span><span>Volume (24h) &nbsp;${icon('144812','imgGroup3')}</span><span>Cleared</span></div>${divider('144812','imgFrame1707478731')}<div class="pairs-grid"><span class="row">${icon('144812','imgUni')}Uniswap V4</span><span>ACME/USDC</span>${icon('144812','imgCurrencyLogo')}<span>$1,324,893</span>${icon('144812','imgStatusActive')}</div>${divider('144812','imgFrame1707478733')}</div></section>`;}
function dashboard(all=false){return `${topbar()}<main class="workspace dashboard"><section class="panel"><div class="panel-heading"><h1 style="font-size:16px;font-weight:400;line-height:24px">Transactions</h1>${all?`<input id="search" type="search" placeholder="Search by Wallet address or Order ID" aria-label="Search transactions" value="${escape(query)}">`:''}</div><div class="table-scroll" tabindex="0" role="region" aria-label="Transactions"><table class="transactions"><thead><tr><th><button class="sort" data-action="sort" aria-label="Sort by amount">Amount ${icon('144812','imgGroup3')}</button></th><th>Status</th><th>Quantity</th><th>Wallet</th><th>Date &nbsp; ${icon('144812','imgGroup3')}</th><th>On-chain tx</th><th>Order ID</th></tr><tr><td colspan="7" style="height:8px">${divider('144812','imgFrame1707478731')}</td></tr></thead><tbody id="transaction-rows">${tableBody()}</tbody></table></div><div class="table-actions">${all?`<button class="outline" data-action="csv">${icon('145661','imgGroup4')}Download CSV</button><div id="pagination">${pagination()}</div>`:'<a href="#transactions" class="outline" style="min-height:50px;background:var(--soft)">View all transactions</a>'}</div></section>${all?'':digital()}</main>${footer()}`;}
const settingsLinks=[['project','Project info'],['digital','Digital asset'],['billing','Billing'],['deactivate','Deactivate account']];
function settings(part){return `${topbar()}<main class="workspace"><div class="split"><aside class="sidebar"><div class="sidebar-heading">Settings<button data-action="dashboard" aria-label="Close settings">${icon('139458','imgClose')}</button></div><nav class="side-nav">${settingsLinks.map(([key,label])=>`<a href="#settings/${key}" class="side-link ${key===part?'active':''}">${label}<span class="arrow">${icon('139458','imgGroup1')}</span></a>`).join('')}</nav></aside><section class="content">${settingsBody(part)}</section></div></main>${footer()}`;}
function upload(kind='project'){const logo=kind==='project'?state.logo:state.assetLogo;return `<div class="logo-setting"><div class="small" style="margin-bottom:10px">${kind==='project'?'Logo':'Image'}</div><button type="button" class="upload" data-upload-kind="${kind}" aria-label="Upload ${kind==='project'?'company logo':'digital asset image'}">${logo?`<img class="preview" src="${logo}" alt="Uploaded ${kind==='project'?'company logo':'digital asset image'}">`:icon('139458','imgImage')}</button></div>`;}
function billingPayment(){return `<div class="billing-payment"><div class="billing-columns"><form id="billing-payment" class="billing-method"><h2>Payment details</h2><input aria-label="Primary payment method" value="ACME" disabled><div class="billing-currencies"><div><div class="small">Secondary payment method</div><div class="billing-usdc">${icon('140366','imgUsdc')}USDC</div></div><div><div class="small">USDC network</div>${network('paymentNetwork',state.paymentNetwork||'Ethereum')}</div></div></form><aside class="billing-callout"><p><strong>Pay with your digital asset</strong><br>Token-based projects can settle their subscription fees using the tokens they have issued for their project.<br><a href="https://help.onchainramp.com/en/articles/10604829-accepted-payment-methods-for-onchain-ramp-subscription" target="_blank" rel="noopener noreferrer">Read more about this</a></p><p><span class="billing-warning">⚠</span> <strong>Sending USDC from a different network than the one selected can result in a permanent loss. Make sure the network matches before proceeding.</strong></p></aside></div><div class="billing-divider">${divider('140366','imgFrame1707478936')}</div><div class="billing-columns"><section class="billing-balance"><h2>Balance</h2><div class="row"><strong>$1200</strong>${icon('140366','imgStatusActive')}</div><p class="muted small">Next payment due 29th April</p></section><section class="billing-deposit"><h2>Billing details</h2><div class="small">Deposit and drawdown address</div><button class="billing-address" data-copy="0x89540000000000000000000000000000009F12A4" aria-label="Copy deposit and drawdown address"><span>0x8954...9F12A4</span>${icon('144812','imgContentCopyFilled1')}</button></section></div></div>`;}
function billingTransactions(){return `<div class="table-scroll" tabindex="0" role="region" aria-label="Subscription payment transactions"><table class="billing-transactions"><caption class="sr-only">Subscription payment transactions</caption><colgroup><col class="billing-type"><col><col><col class="billing-date"><col class="billing-status"></colgroup><thead><tr>${['Type','Amount','Paid with','Initiated at','Status'].map(t=>`<th scope="col">${t}</th>`).join('')}</tr><tr aria-hidden="true" class="billing-separator"><td colspan="5">${divider('140860','imgFrame1707478731')}</td></tr></thead><tbody>${Array.from({length:9},(_,i)=>{const currency=[0,4,7].includes(i)?'USDC':'ACME';const failed=[2,5,8].includes(i);return `<tr><td>Starter plan monthly payment</td><td>$200</td><td><span class="billing-currency">${currency==='USDC'?icon('140860','imgUsdc'):digitalAssetLogo()}${currency}</span></td><td>Sep 1, 2024, 10:10 PM</td><td><span class="billing-result">${icon('140860',failed?'imgStatusInactive':'imgStatusActive')}${failed?'Failed':'Completed'}</span></td></tr><tr aria-hidden="true" class="billing-separator"><td colspan="5">${divider('140860','imgFrame1707478732')}</td></tr>`;}).join('')}</tbody></table></div>`;}
function billing(){const tab=route.split('/')[2]||'plan';return `<div class="billing-screen"><h1>Billing</h1><nav class="tabs billing-tabs" aria-label="Billing sections">${[['plan','Plan'],['payment','Payment details'],['transactions','Transactions']].map(([key,title])=>`<a href="#settings/billing/${key}" ${key===tab?'aria-current="page" class="active"':''}>${title}</a>`).join('')}</nav><div id="billing-body">${tab==='payment'?billingPayment():tab==='transactions'?billingTransactions():`<article class="plan" style="width:286px;min-height:212px"><h3>Starter</h3><div class="price">$200<small> / month</small></div><button class="primary" disabled style="background:var(--soft);color:var(--pale);margin-top:16px">Selected</button></article>`}</div></div>`;}
function settingsBody(part){if(part==='project')return `<h1>Project info</h1><div class="section-line">${divider('139458','imgFrame1707478936')}</div><form id="project" class="settings-form"><div class="image-field">${upload()}${field('Company name','company','','text',state.company,'required')}</div><div class="two-col">${field('Full name','name','','text',state.name,'required')}${field('Email','email','','email',state.email||'john@acme.com','disabled')}</div><div class="save-wrap hidden">${primary('Save changes')}</div></form>`;
 if(part==='digital')return `<h1>Digital asset details</h1><div class="section-line">${divider('139827','imgFrame1707478936')}</div><form id="digital" class="settings-form"><div class="image-field">${upload('digital')}${field('Ticker','ticker','','text','ACME','disabled')}</div><div class="two-col">${field('Website','website','','url',state.website,'required')}${field('Link to whitepaper','whitepaper','','url',state.whitepaper||'https://acme.com/whitepaper','required')}</div><label class="field">Description<textarea name="description" placeholder="Add your digital asset description in here..." required>${escape(state.description)}</textarea></label><div>${primary('Save description')}</div></form>`;
 if(part==='billing')return billing();
 return `<h1>Deactivate account</h1><div class="section-line">${divider('139458','imgFrame1707478936')}</div><div class="danger-copy"><p>Deactivating your account will temporarily disable access, but don’t worry — you can reactivate it anytime by simply logging back in.</p><p>We’ll keep your information safe while your account is inactive, and no one will be able to access it during this time.</p></div><button class="danger" data-action="deactivate">Deactivate account</button>`;
}
function render(){const previousRoute=route;const previousProgress=app.querySelector('.progress')?.dataset.displayed;route=location.hash.slice(1)||'signin';document.title='ONCHAIN Ramp · '+(screenOptions.find(s=>s[0]===route)?.[1]||'Business');let content;if(route==='signin')content=signIn();else if(route==='verify')content=verify();else if(route==='details')content=company();else if(route==='asset')content=asset();else if(route.startsWith('setup/'))content=setup(route.split('/')[1]);else if(route.startsWith('settings/'))content=settings(route.split('/')[1]);else content=dashboard(route==='transactions');app.innerHTML=content+prototypeNav();animateProgress(previousProgress);updateForms();animateScreen(previousRoute);if(previousRoute!==route)window.scrollTo(0,0);}
function animateScreen(previousRoute){
 if(!previousRoute||previousRoute===route||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 // Keep shared navigation and the setup progress bar steady while the content changes.
 const sharedBilling=previousRoute.startsWith('settings/billing')&&route.startsWith('settings/billing');
 const sharedPanel=['settings/','setup/'].some(prefix=>previousRoute.startsWith(prefix)&&route.startsWith(prefix));
 const authPair=['signin','verify'].includes(previousRoute)&&['signin','verify'].includes(route);
 const target=app.querySelector(sharedBilling?'#billing-body':sharedPanel?'.content':authPair?'.login-card':'.auth-main, .workspace');
 if(!target)return;
 // Individual translate preserves the card's existing positioning transform.
 target.animate([{opacity:0,translate:'0 10px'},{opacity:1,translate:'0 0'}],{duration:320,easing:'cubic-bezier(.22,1,.36,1)'});
}
let progressAnimation;
function animateProgress(previous){
 cancelAnimationFrame(progressAnimation);
 const bar=app.querySelector('.progress');if(!bar)return;
 const target=Number(bar.dataset.progress);
 const start=previous===undefined?target:Number(previous);
 const paint=value=>{bar.dataset.displayed=value;bar.querySelector('.fill').style.width=value+'%';bar.querySelector('span').style.width=value+'%';bar.querySelector('span').textContent=Math.round(value)+'%';};
 const finish=()=>{if(target===100)bar.classList.add('complete');};
 if(start===target||matchMedia('(prefers-reduced-motion: reduce)').matches){paint(target);finish();return;}
 paint(start);const began=performance.now();
 const tick=now=>{const t=Math.min(1,(now-began)/650);const eased=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;paint(start+(target-start)*eased);if(t<1)progressAnimation=requestAnimationFrame(tick);else finish();};
 progressAnimation=requestAnimationFrame(tick);
}
function updateForms(){const taxes=[...app.querySelectorAll('input[name=tax]')];const na=taxes.find(input=>input.value==='N/A');if(na){taxes.filter(input=>input!==na).forEach(input=>{input.disabled=na.checked;if(na.checked)input.checked=false;});na.setCustomValidity(taxes.some(input=>input.checked)?'':'Select a tax option or N/A.');}app.querySelectorAll('form').forEach(form=>{const btn=form.querySelector('button.primary[type="submit"],button.primary:not([type])');if(btn)btn.disabled=!form.checkValidity();});}
function refreshTable(){document.querySelector('#transaction-rows').innerHTML=tableBody();const p=document.querySelector('#pagination');if(p)p.innerHTML=pagination();}
app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;page=1;refreshTable();return;}const form=e.target.closest('form');if(form?.id==='whitepaper'||form?.id==='payment')form.querySelector('.continue-wrap')?.classList.remove('hidden');if(form?.id==='project')form.querySelector('.save-wrap').classList.remove('hidden');if(e.target.closest('.otp')){e.target.value=e.target.value.replace(/\D/g,'').slice(-1);if(e.target.value)e.target.nextElementSibling?.matches('input')?e.target.nextElementSibling.focus():e.target.nextElementSibling?.nextElementSibling?.focus();document.querySelector('#otp-error').textContent='';}updateForms();});
app.addEventListener('keydown',e=>{if(e.target.closest('.otp')&&e.key==='Backspace'&&!e.target.value){const inputs=[...document.querySelectorAll('.otp input')];inputs[inputs.indexOf(e.target)-1]?.focus();}});
app.addEventListener('paste',e=>{if(!e.target.closest('.otp'))return;const digits=e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6);if(digits.length>1){e.preventDefault();document.querySelectorAll('.otp input').forEach((el,i)=>el.value=digits[i]||'');document.querySelectorAll('.otp input')[Math.min(digits.length,5)].focus();updateForms();}});
app.addEventListener('change',e=>{if(e.target.matches('[aria-label="Preview screen"]')){go(e.target.value);return;}if(e.target.id==='email-owner'){const form=e.target.form;form.elements.owner.disabled=!e.target.checked;updateForms();}if(e.target.name==='paymentNetwork'){state.paymentNetwork=e.target.value;e.target.closest('form').querySelector('.continue-wrap')?.classList.remove('hidden');updateForms();}});
app.addEventListener('submit',e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));switch(form.id){case 'signin':state.email=data.email;go('verify');toast('Demo confirmation code: 371824');break;case 'verify':if(Object.values(data).join('')!=='371824'){document.querySelector('#otp-error').textContent='Incorrect code. Use 371824 for this prototype.';return;}if(state.inactive){state.inactive=false;go('dashboard');toast('Demo account reactivated.');}else go('details');break;case 'details':Object.assign(state,data);go('asset');break;case 'asset':Object.assign(state,{network:data.network,address:data.address,taxes:new FormData(form).getAll('tax'),completed:1});go('setup/whitepaper');break;case 'whitepaper':state.whitepaper=data.whitepaper;state.completed=Math.max(state.completed,2);go('setup/payment');break;case 'payment':state.paymentNetwork=data.paymentNetwork;state.completed=Math.max(state.completed,3);go('setup/plan');break;case 'owner':modal('Verification email prepared',`<p>This demo represents sending a verification request to <strong>${escape(data.owner)}</strong>. No email has been sent.</p>`,primary('Simulate owner verification','data-action="finish-verification"'));break;case 'project':case 'digital':Object.assign(state,data);render();toast('Changes saved for this session.');break;}});
async function copy(value){try{await navigator.clipboard.writeText(value);toast('Copied to clipboard.');}catch{modal('Copy value',`<p>Copy this value:</p><input readonly value="${escape(value)}" aria-label="Value to copy">`);}}
document.addEventListener('click',async e=>{const button=e.target.closest('[data-action],[data-go],[data-copy],[data-page]');if(!button)return;if(button.dataset.go){go(button.dataset.go);return;}if(button.dataset.copy){await copy(button.dataset.copy);return;}if(button.dataset.page){page=Number(button.dataset.page);refreshTable();return;}const action=button.dataset.action;
 if(action==='close')dialog.close();
 else if(action==='menu'){const nav=document.querySelector('.account-menu');nav.classList.toggle('hidden');button.setAttribute('aria-expanded',String(!nav.classList.contains('hidden')));}
 else if(action==='dashboard')go('dashboard');
 else if(action==='restart'){for(const logo of [state.logo,state.assetLogo])if(logo)URL.revokeObjectURL(logo);state={...initial};query='';page=1;sortDirection=0;go('signin');}
 else if(action==='signout'){go('signin');toast('Signed out of the demo.');}
 else if(action==='ramp')modal('Your Ramp link','<p>The business ramp link is available here in the product. This prototype uses a demo link.</p><input readonly value="https://ramp.example/acme" aria-label="Demo ramp link">',`<div class="continue-wrap">${primary('Copy link','data-copy="https://ramp.example/acme"')}</div>`);
 else if(action==='resend')toast('Demo code: 371824. No email is sent.');
 else if(action==='choose-plan'){state.completed=Math.max(state.completed,4);go('setup/verification');}
 else if(action==='verify-x')modal('Verify project ownership','<p>This prototype simulates verification with your project’s official X account. No account connection is required.</p>',primary('Simulate verification','data-action="finish-verification"'));
 else if(action==='finish-verification'){dialog.close();state.completed=5;render();}
 else if(action==='sort'){sortDirection=sortDirection===1?-1:1;page=1;refreshTable();button.setAttribute('aria-label',`Sort by amount (${sortDirection===1?'ascending':'descending'})`);}
 else if(action==='csv'){const data=filtered();const csv=['Amount,Currency,Status,Quantity,Wallet,Date,On-chain tx,Order ID',...data.map(r=>[r.amount,'USD',r.status,r.quantity,r.wallet,r.date,r.tx,r.order].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='onchain-transactions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`Exported ${data.length} demo transactions.`);}
 else if(action==='deactivate')openDeactivation();
 else if(action==='terms'||action==='privacy')modal(action==='terms'?'Terms and Conditions':'Privacy Policy','<p>This is a local interactive prototype, not a live service. Enter sample information only. Form data is held in memory and clears when the page reloads. No payments, emails, or account changes are sent to external services.</p>');
 else if(action==='support')modal('How can we help?','<p>Explore the business flow using the screen selector at the bottom. For email confirmation, use <strong>371824</strong>. Forms and account actions are simulated.</p>',`<div class="row">${primary('Go to setup','data-action="support-setup"')}<button class="outline" data-action="close">Close</button></div>`);
 else if(action==='support-setup'){dialog.close();go('setup/whitepaper');}
 else if(action==='payment-info')modal('Pay with your digital asset','<p>Your subscription can be paid using the project token, with USDC as a secondary payment currency. Select a network to continue the demo. No wallet connection or transfer is made.</p>');

});
document.addEventListener('click',e=>{if(!e.target.closest('.account-wrap')){document.querySelector('.account-menu')?.classList.add('hidden');document.querySelector('.account-toggle')?.setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.account-menu')?.classList.add('hidden');document.querySelector('.account-toggle')?.setAttribute('aria-expanded','false');}});
function closeNetworks(except=null){document.querySelectorAll('.network-select').forEach(el=>{if(el===except)return;el.querySelector('.network-options').classList.add('hidden');el.querySelector('.network-trigger').setAttribute('aria-expanded','false');});}
function openNetwork(el,last=false){closeNetworks(el);el.querySelector('.network-options').classList.remove('hidden');el.querySelector('.network-trigger').setAttribute('aria-expanded','true');const options=[...el.querySelectorAll('[role=option]')];(options.find(o=>o.getAttribute('aria-selected')==='true')||options[last?options.length-1:0]).focus();}
app.addEventListener('click',e=>{const trigger=e.target.closest('.network-trigger');const option=e.target.closest('[data-network]');if(trigger){const el=trigger.closest('.network-select');if(trigger.getAttribute('aria-expanded')==='true')closeNetworks();else openNetwork(el);}if(option){const el=option.closest('.network-select');const select=el.querySelector('select');select.value=option.dataset.network;el.querySelector('.network-value').innerHTML=networkLogo(select.value)+escape(select.value);el.querySelector('.network-value').classList.remove('muted');el.querySelectorAll('[role=option]').forEach(o=>o.setAttribute('aria-selected',String(o===option)));closeNetworks();el.querySelector('.network-trigger').focus();select.dispatchEvent(new Event('input',{bubbles:true}));select.dispatchEvent(new Event('change',{bubbles:true}));}});
app.addEventListener('keydown',e=>{const el=e.target.closest('.network-select');if(!el)return;const trigger=el.querySelector('.network-trigger');const options=[...el.querySelectorAll('[role=option]')];const index=options.indexOf(e.target);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(trigger.getAttribute('aria-expanded')==='false'){openNetwork(el,e.key==='ArrowUp');return;}const next=e.key==='Home'?0:e.key==='End'?options.length-1:(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;options[next].focus();}else if(e.key==='Escape'){e.preventDefault();closeNetworks();trigger.focus();}else if(e.key==='Tab')closeNetworks();else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey){options.find(o=>o.dataset.network.toLowerCase().startsWith(e.key.toLowerCase()))?.focus();}});
document.addEventListener('click',e=>{if(!e.target.closest('.network-select'))closeNetworks();});
const deactivateDialog=document.createElement('dialog');
deactivateDialog.className='deactivation-dialog';
deactivateDialog.setAttribute('aria-labelledby','deactivation-heading');
document.body.append(deactivateDialog);
let deactivationStep='reason',deactivationReason='',deactivationNote='';
function openDeactivation(){deactivationReason='';deactivationNote='';showDeactivation('reason');deactivateDialog.showModal();}
function showDeactivation(step){
 deactivationStep=step;
 if(step==='reason'){
  const reasons=['I no longer use the service','Privacy or security concerns','Too many emails or notifications','Technical issues or poor user experience','Found a better alternative','Other reason'];
  deactivateDialog.innerHTML=`<h2 id="deactivation-heading">Before you go, tell us why you are leaving</h2><form id="deactivation-reason"><fieldset class="deactivation-reasons"><legend class="sr-only">Reason for leaving</legend>${reasons.map(reason=>`<label><input type="radio" name="reason" value="${reason}"><span>${reason}</span></label>`).join('')}</fieldset><textarea name="note" aria-label="Tell us your reason" placeholder="Tell us your reason"></textarea><button class="danger full" disabled>Continue to deactivate account</button></form><button class="deactivation-secondary" data-deactivation="skip">Skip</button>`;
 }else if(step==='confirm'){
  deactivateDialog.innerHTML=`<h2 id="deactivation-heading">Deactivate account</h2><p class="deactivation-subtitle">Are you sure you want to Deactivate your account?</p><div class="deactivation-explanation"><p>Deactivating your account is a temporary action — you can come back and reactivate it anytime just by logging in. While your account is suspended:</p><p>You will lose access to all features and services tied to your account.</p><p>You won’t be able to share your ramp link or view your ONCHAIN® transactions.</p><p>Any active or scheduled activity will be paused or canceled.</p><p>You will stop receiving emails and notifications from us.</p><p>However, your data and preferences will be safely stored, and nothing will be deleted. When you're ready to return, everything will be right where you left it.</p><p>If you're sure, confirm below to suspend your account.</p></div><form id="deactivation-confirm"><label class="check deactivation-acknowledgement"><input type="checkbox" name="acknowledge" required><span>I understand that suspending my account is temporary and my data will be saved.</span></label><button class="danger full" disabled>Deactivate account</button></form>`;
 }else{
  deactivateDialog.innerHTML=`<h2 id="deactivation-heading">Your request to deactivate your<br>account has been received 😔</h2><p class="deactivation-subtitle">Your account is now inactive. An email confirmation has been sent, and you can reactivate your account at any time by logging back in.</p><button class="primary full" data-deactivation="reactivate">Reactivate account</button><button class="deactivation-secondary" data-deactivation="close">Close</button>`;
 }
 if(deactivateDialog.open){deactivateDialog.querySelector('h2').tabIndex=-1;deactivateDialog.querySelector('h2').focus({preventScroll:true});}
}
deactivateDialog.addEventListener('input',()=>{
 const form=deactivateDialog.querySelector('form');if(!form)return;
 if(deactivationStep==='reason'){const values=new FormData(form);const reason=values.get('reason');form.querySelector('button').disabled=!reason||(reason==='Other reason'&&!String(values.get('note')).trim());}
 else form.querySelector('button').disabled=!form.elements.acknowledge.checked;
});
deactivateDialog.addEventListener('submit',e=>{
 e.preventDefault();const form=e.target;if(form.querySelector('button').disabled||!form.reportValidity())return;
 if(deactivationStep==='reason'){const values=new FormData(form);deactivationReason=values.get('reason');deactivationNote=String(values.get('note')).trim();showDeactivation('confirm');}
 else{state.inactive=true;state.deactivationFeedback={reason:deactivationReason,note:deactivationNote};showDeactivation('complete');}
});
deactivateDialog.addEventListener('click',e=>{
 const action=e.target.closest('[data-deactivation]')?.dataset.deactivation;
 if(action==='skip'){showDeactivation('confirm');}
 else if(action==='close')deactivateDialog.close();
 else if(action==='reactivate'){state.inactive=false;deactivateDialog.close();go('dashboard');toast('Demo account reactivated.');}
});
deactivateDialog.addEventListener('close',()=>{if(state.inactive)go('signin');});
const uploadDialog=document.createElement('dialog');
uploadDialog.className='image-upload-dialog';
uploadDialog.setAttribute('aria-labelledby','upload-heading');
document.body.append(uploadDialog);
let imageDraft=null,uploadKey=null,uploadRevision=0;
function openImageUpload(kind){
 uploadKey=kind==='digital'?'assetLogo':'logo';imageDraft=null;
 const current=state[uploadKey];
 uploadDialog.innerHTML=`<h2 id="upload-heading" class="sr-only">Upload ${kind==='digital'?'digital asset image':'company logo'}</h2><div class="image-upload-row"><div class="image-upload-preview">${current?`<img class="draft-image" src="${current}" alt="Current image">`:`<div class="image-upload-placeholder">${icon('139622','imgImage2')}</div>`}</div><button type="button" class="image-dropzone" aria-label="Choose an image to upload"><span class="image-upload-cloud">${icon('139622','imgGroup2')}</span><span><span class="upload-instruction"><strong>Click to upload</strong> or drag and drop</span><span class="upload-hint">Use a square image for best results</span></span></button><input type="file" id="upload-image-file" class="hidden" accept="image/png,image/jpeg,image/webp" aria-label="Image file"></div><p class="image-upload-error hidden" role="alert"></p><div class="image-upload-actions"><button type="button" class="outline" data-upload-cancel>Cancel</button><button type="button" class="primary" data-upload-save disabled>Save</button></div>`;
 uploadDialog.showModal();
}
async function stageImage(file){
 if(!file)return;
 const revision=++uploadRevision;
 const error=uploadDialog.querySelector('.image-upload-error');
 const save=uploadDialog.querySelector('[data-upload-save]');
 const fail=message=>{error.textContent=message;error.classList.remove('hidden');save.disabled=!imageDraft;};
 if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5e6){fail('Choose a PNG, JPG, or WebP image smaller than 5 MB.');return;}
 save.disabled=true;
 const url=URL.createObjectURL(file);
 try{const preview=new Image();preview.src=url;await preview.decode();}
 catch{URL.revokeObjectURL(url);if(revision===uploadRevision&&uploadDialog.open)fail('This image could not be opened. Please choose another file.');return;}
 if(revision!==uploadRevision||!uploadDialog.open){URL.revokeObjectURL(url);return;}
 if(imageDraft)URL.revokeObjectURL(imageDraft);
 imageDraft=url;error.classList.add('hidden');
 uploadDialog.querySelector('.image-upload-preview').innerHTML=`<img class="draft-image" src="${url}" alt="Selected image preview">`;
 save.disabled=false;
}
document.addEventListener('click',e=>{const trigger=e.target.closest('[data-upload-kind]');if(trigger)openImageUpload(trigger.dataset.uploadKind);});
uploadDialog.addEventListener('click',e=>{
 if(e.target.closest('.image-dropzone'))uploadDialog.querySelector('input[type=file]').click();
 if(e.target.closest('[data-upload-cancel]'))uploadDialog.close();
 if(e.target.closest('[data-upload-save]')&&imageDraft){
  const key=uploadKey,kind=key==='logo'?'project':'digital';
  if(state[key])URL.revokeObjectURL(state[key]);state[key]=imageDraft;imageDraft=null;
  const setting=app.querySelector(`[data-upload-kind="${kind}"]`)?.closest('.logo-setting');
  if(setting)setting.outerHTML=upload(kind);
  if(key==='logo'){const header=app.querySelector('.project-logo');if(header)header.outerHTML=`<span class="project-logo"><img src="${state.logo}" alt="Company logo"></span>`;}
  uploadDialog.close();toast(key==='logo'?'Company logo updated.':'Digital asset image updated.');
 }
});
uploadDialog.addEventListener('change',e=>{if(e.target.type==='file'){stageImage(e.target.files[0]);e.target.value='';}});
for(const event of ['dragenter','dragover'])uploadDialog.addEventListener(event,e=>{e.preventDefault();uploadDialog.querySelector('.image-dropzone').classList.add('dragging');});
uploadDialog.addEventListener('dragleave',e=>{if(!uploadDialog.contains(e.relatedTarget))uploadDialog.querySelector('.image-dropzone').classList.remove('dragging');});
uploadDialog.addEventListener('drop',e=>{e.preventDefault();uploadDialog.querySelector('.image-dropzone').classList.remove('dragging');stageImage(e.dataTransfer.files[0]);});
uploadDialog.addEventListener('close',()=>{uploadRevision++;if(imageDraft)URL.revokeObjectURL(imageDraft);imageDraft=null;uploadKey=null;});
window.addEventListener('hashchange',()=>{if(uploadDialog.open)uploadDialog.close();if(route==='transactions'){query='';page=1;}render();});
render();
