import { chromium } from '/Users/gustavoguerra/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
if(process.argv.includes('--billing')){await import('./verify-billing.mjs');process.exit(0);}
if(process.argv.includes('--progress')){await import('./verify-progress.mjs');process.exit(0);}
if(process.argv.includes('--upload')){await import('./verify-upload.mjs');process.exit(0);}
if(process.argv.includes('--deactivation')){await import('./verify-deactivation.mjs');process.exit(0);}
const browser=await chromium.launch({headless:true,channel:'chrome'});
try{
const page=await browser.newPage({viewport:{width:1440,height:810},acceptDownloads:true});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4174');await page.screenshot({path:'/private/tmp/b2b-signin.png'});
await page.getByRole('textbox',{name:'Your Email'}).fill('demo@example.com');await page.getByRole('button',{name:'Continue',exact:true}).click();
for(let i=0;i<6;i++)await page.getByRole('textbox',{name:`Code digit ${i+1}`}).fill('0');
await page.getByRole('button',{name:'Continue',exact:true}).click();assert.match(await page.locator('#otp-error').textContent(),/Incorrect/);
for(let i=0;i<6;i++)await page.getByRole('textbox',{name:`Code digit ${i+1}`}).fill('371824'[i]);
await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.getByLabel('Full name',{exact:true}).fill('John Smith');await page.getByLabel('Company name',{exact:true}).fill('ACME Protocol');await page.getByLabel('Digital asset website').fill('https://acme.com');await page.getByRole('button',{name:'Continue',exact:true}).click();
await page.getByRole('combobox',{name:'Network',exact:true}).click();await page.getByRole('option',{name:'Ethereum',exact:true}).click();await page.getByLabel('Address',{exact:true}).fill('invalid');const buyTax=page.getByLabel('Buy tax',{exact:true}),sellTax=page.getByLabel('Sell tax',{exact:true}),noTax=page.getByLabel('N/A',{exact:true});await buyTax.check();await sellTax.check();assert(await buyTax.isChecked());assert(await sellTax.isChecked());assert(!(await noTax.isChecked()));await noTax.check();assert(await buyTax.isDisabled());assert(await sellTax.isDisabled());assert(!(await buyTax.isChecked()));assert(!(await sellTax.isChecked()));await noTax.uncheck();assert(await buyTax.isEnabled());assert(await sellTax.isEnabled());assert.equal(await page.locator('#asset').evaluate(f=>f.checkValidity()),false);await noTax.check();await page.locator('[name=agreement0]').check();await page.locator('[name=agreement1]').check();assert(await page.getByRole('button',{name:'Complete sign up'}).isDisabled());
await page.getByLabel('Address',{exact:true}).fill('0x2c00000000000000000000000000000000004567');await page.getByRole('button',{name:'Complete sign up'}).click();
await page.getByLabel('Your whitepaper link').fill('https://acme.com/whitepaper');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('combobox',{name:'Payment network'}).click();await page.getByRole('option',{name:'Polygon',exact:true}).click();assert.equal(await page.locator('[name=paymentNetwork]').inputValue(),'Polygon');await page.getByRole('combobox',{name:'Payment network'}).press('ArrowDown');await page.keyboard.press('Home');await page.keyboard.press('Enter');assert.equal(await page.locator('[name=paymentNetwork]').inputValue(),'Ethereum');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('button',{name:'Choose Starter'}).click();await page.getByRole('button',{name:/Sign in$/}).click();await page.getByRole('button',{name:'Simulate verification',exact:true}).click();
await page.screenshot({path:'/private/tmp/b2b-dashboard.png',fullPage:true});
await page.getByRole('link',{name:'View all transactions'}).click();
await page.getByRole('searchbox',{name:'Search transactions'}).fill('no-match');assert.match(await page.locator('#transaction-rows').textContent(),/No transactions found/);
await page.getByRole('searchbox',{name:'Search transactions'}).fill('Failed');assert.equal(await page.locator('#transaction-rows .status').count(),10);assert.equal(await page.locator('#transaction-rows .status.Failed').count(),10);
const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Download CSV'}).click();const download=await dl;assert.equal(download.suggestedFilename(),'onchain-transactions.csv');
await page.getByRole('searchbox',{name:'Search transactions'}).fill('');await page.getByRole('button',{name:'Next page'}).click();assert.equal(await page.locator('[aria-current=page]').textContent(),'2');
const routes=['signin','verify','details','asset','setup/whitepaper','setup/payment','setup/plan','setup/verification','dashboard','transactions','settings/project','settings/digital','settings/billing','settings/deactivate'];
for(const r of routes){await page.goto('http://127.0.0.1:4174/#'+r);await page.evaluate(()=>document.fonts.ready);await page.locator('img').first().waitFor();await page.waitForFunction(()=>[...document.images].every(i=>i.complete));const audit=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),sized:[...document.images].filter(i=>i.width===0||i.height===0).map(i=>i.src)}));assert.deepEqual(audit,{overflow:false,broken:[],sized:[]},r);if(['setup/plan','setup/whitepaper','settings/project'].includes(r))await page.screenshot({path:'/private/tmp/b2b-'+r.replace('/','-')+'.png',fullPage:true});}
await page.goto('http://127.0.0.1:4174/#settings/project');await page.getByLabel('Company name',{exact:true}).fill('Updated ACME');await page.getByRole('button',{name:'Save changes'}).click();assert.match(await page.locator('.project-brand').textContent(),/Updated ACME/);
await page.setViewportSize({width:390,height:844});for(const r of ['signin','dashboard','setup/whitepaper','settings/project']){await page.goto('http://127.0.0.1:4174/#'+r);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile '+r);}
await page.setViewportSize({width:1440,height:870});await page.goto('http://127.0.0.1:4174/#dashboard');await page.locator('.pairs-grid').last().waitFor();await page.waitForFunction(()=>[...document.images].every(i=>i.complete));await page.screenshot({path:'/private/tmp/b2b-dashboard-final.png',fullPage:true});
console.log(await page.evaluate(()=>({height:document.documentElement.scrollHeight,digital:document.querySelector('.digital').getBoundingClientRect().toJSON(),font:getComputedStyle(document.querySelector('.description')).font})));
await page.goto('http://127.0.0.1:4174/#setup/payment');await page.getByRole('combobox',{name:'Payment network'}).click();await page.waitForFunction(()=>[...document.images].every(i=>i.complete));await page.locator('.network-options').screenshot({path:'/private/tmp/b2b-network-dropdown.png'});assert.equal(await page.locator('.network-options img').count(),2);await page.keyboard.press('Escape');assert.equal(await page.getByRole('combobox',{name:'Payment network'}).getAttribute('aria-expanded'),'false');assert.deepEqual(errors,[]);console.log('PASS: onboarding, invalid/correct codes, address validation, setup, search, pagination, CSV, settings, 14 route asset audits, mobile overflow, and console errors.');
}finally{await browser.close();}
